name: pearlhub_admin
description: PearlHub Admin App
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.5.0
  pearlhub_shared:
    path: ../shared
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1

flutter:
  uses-material-design: true
