name: pearlhub_provider
description: PearlHub Provider App
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.5.0
  pearlhub_shared:
    path: ../shared
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.0.7
  fl_chart: ^0.67.0

flutter:
  uses-material-design: true
